@echo off
REM Shared language setup for batch launchers.
REM UEFI_BINARY_TOOL_LANG=ko or en overrides the OS language.

set "TOOL_VENDOR=%~1"
set "UBT_LANG="

if /I "%UEFI_BINARY_TOOL_LANG%"=="ko" set "UBT_LANG=ko"
if /I "%UEFI_BINARY_TOOL_LANG%"=="en" set "UBT_LANG=en"

if not defined UBT_LANG (
    for /f "usebackq delims=" %%L in (`powershell -NoProfile -ExecutionPolicy Bypass -Command "try { $c = Get-Culture; $c.TwoLetterISOLanguageName } catch { 'en' }" 2^>nul`) do set "UBT_LANG=%%L"
)

if /I "%UBT_LANG%"=="ko" (
    call :ko
) else (
    call :en
)

goto :eof

:ko
set "PYTHON_MISSING_1=[ERROR] Python이 설치되지 않았거나 PATH에 설정되지 않았습니다."
set "PYTHON_MISSING_2=Python 3.6 이상을 설치하고 PATH에 추가해주세요."
set "PYTHON_DOWNLOAD=Python 다운로드: https://www.python.org/downloads/"
set "PYTHON_OK=[OK] Python 확인 완료"
set "REQUIRED_MISSING=[ERROR] 다음 필수 파일들을 찾을 수 없습니다:"
set "REQUIRED_HINT=모든 필수 파일들이 올바른 위치에 있는지 확인해주세요."
set "REQUIRED_OK=[OK] 모든 필수 파일 확인 완료"
set "MAIN_MENU=메인 메뉴"
set "TIP_USAGE=[TIP] 사용 방법:"
set "TIP_MENU=  - 또는 아래 메뉴에서 원하는 기능을 선택하세요"
set "DRAG_MODE=[DRAG DROP] 드래그 앤 드롭 모드"
set "INTERACTIVE_MODE=[INTERACTIVE] 대화형 모드"
set "PASSED_FILE=전달된 파일:"
set "FILE_PATH=파일 경로:"
set "FILE_NOT_FOUND=[ERROR] 전달된 파일을 찾을 수 없습니다."
set "FILE_LABEL=파일:"
set "FILE_OK_MENU=[OK] 파일 확인 완료. 메뉴를 선택하세요..."
set "MENU_TITLE=기능 선택 메뉴"
set "MENU3=3. [종료] 프로그램 종료"
set "PROMPT_CHOICE=선택하세요 (1-3): "
set "INVALID_CHOICE=[ERROR] 잘못된 선택입니다. 1-3 중에서 선택해주세요."
set "EXITING=프로그램을 종료합니다."
set "ANALYZE_START=[ANALYZE] BIOS 파일 분석을 시작합니다..."
set "REPACK_START=[REPACK] 이미지 리패킹을 시작합니다..."
set "ANALYZE_SUCCESS=[SUCCESS] 파일 분석이 성공적으로 완료되었습니다!"
set "REPACK_SUCCESS=[SUCCESS] 이미지 리패킹이 성공적으로 완료되었습니다!"
set "ANALYZE_MODE=BIOS 파일 분석 모드입니다."
set "REPACK_MODE=이미지 리패킹 모드입니다."
set "ERROR_WITH_CODE=[ERROR] 작업 중 오류가 발생했습니다. 종료 코드:"
set "OP_COMPLETE=작업 완료"
set "CONTINUE_PROMPT=다른 작업을 수행하시겠습니까? (Y/N): "
set "DONE=작업을 완료했습니다."
set "CLOSE_PROMPT=이 창을 닫으려면 아무 키나 누르세요..."
set "GENERATED_FILES=생성된 파일들을 확인하세요:"
set "PROJECT_ROOT_LABEL=프로젝트 루트:"
set "EXTRACT_MISSING=[ERROR] 추출된 이미지 폴더를 찾을 수 없습니다:"
set "EXTRACT_HINT=먼저 이미지를 추출하거나, 올바른 추출 폴더가 있는지 확인하세요."
set "REPACK_TARGET=리패킹 대상:"

if /I "%TOOL_VENDOR%"=="ASUS" (
    set "TITLE=ASUS BIOS 이미지 분석/리패킹 도구"
    set "BANNER_TITLE=ASUS BIOS 이미지 분석/리패킹 도구 v3.0"
    set "TIP_DRAG=  - 분석할 ASUS BIOS 파일을 이 배치 파일로 끌어놓으세요"
    set "MENU1=1. [분석] ASUS BIOS 파일 분석"
    set "MENU1D1=   - 파일 구조 분석, 매직 바이트 검사"
    set "MENU1D2=   - ASUS Packer 형식 감지"
    set "MENU1D3=   - 분석 보고서 생성 TXT/MD"
    set "MENU2=2. [리패킹] ASUS 이미지 리패킹"
    set "MENU2D1=   - 수정된 이미지로 재패키징"
    set "MENU2D2=   - 원본 구조 최대 보존"
    set "MENU2D3=   - 크기 변화 자동 처리"
    set "ANALYZE_HEADER=[ANALYZE] ASUS BIOS 파일 분석"
    set "REPACK_HEADER=[REPACK] ASUS 이미지 리패킹"
) else (
    set "TITLE=MSI BIOS 분석/리패킹 도구"
    set "BANNER_TITLE=MSI BIOS Section Binary 분석/리패킹 도구 v1.0"
    set "TIP_DRAG=  - 분석할 MSI BIOS 파일을 이 배치 파일로 끌어놓으세요"
    set "MENU1=1. [분석] MSI BIOS 파일 분석"
    set "MENU1D1=   - MSI Packer 구조 분석"
    set "MENU1D2=   - 이미지 타입 및 매직 바이트 검사"
    set "MENU1D3=   - 분석 보고서 생성"
    set "MENU2=2. [리패킹] MSI 이미지 리패킹"
    set "MENU2D1=   - 추출된 이미지로 재패키징"
    set "MENU2D2=   - 원본 구조 보존"
    set "MENU2D3=   - msi_extracted 폴더 필요"
    set "ANALYZE_HEADER=[ANALYZE] MSI BIOS 파일 분석"
    set "REPACK_HEADER=[REPACK] MSI 이미지 리패킹"
)
goto :eof

:en
set "PYTHON_MISSING_1=[ERROR] Python is not installed or is not available in PATH."
set "PYTHON_MISSING_2=Install Python 3.6 or later and add it to PATH."
set "PYTHON_DOWNLOAD=Python download: https://www.python.org/downloads/"
set "PYTHON_OK=[OK] Python check completed"
set "REQUIRED_MISSING=[ERROR] The following required files were not found:"
set "REQUIRED_HINT=Check that all required files are in the correct locations."
set "REQUIRED_OK=[OK] All required files found"
set "MAIN_MENU=Main Menu"
set "TIP_USAGE=[TIP] Usage:"
set "TIP_MENU=  - Or choose a function from the menu below"
set "DRAG_MODE=[DRAG DROP] Drag and drop mode"
set "INTERACTIVE_MODE=[INTERACTIVE] Interactive mode"
set "PASSED_FILE=Passed file:"
set "FILE_PATH=File path:"
set "FILE_NOT_FOUND=[ERROR] The passed file was not found."
set "FILE_LABEL=File:"
set "FILE_OK_MENU=[OK] File found. Choose a menu item..."
set "MENU_TITLE=Function Menu"
set "MENU3=3. [Exit] Exit program"
set "PROMPT_CHOICE=Choose (1-3): "
set "INVALID_CHOICE=[ERROR] Invalid choice. Choose 1-3."
set "EXITING=Exiting program."
set "ANALYZE_START=[ANALYZE] Starting BIOS file analysis..."
set "REPACK_START=[REPACK] Starting image repack..."
set "ANALYZE_SUCCESS=[SUCCESS] File analysis completed successfully."
set "REPACK_SUCCESS=[SUCCESS] Image repack completed successfully."
set "ANALYZE_MODE=BIOS file analysis mode."
set "REPACK_MODE=Image repack mode."
set "ERROR_WITH_CODE=[ERROR] Operation failed. Exit code:"
set "OP_COMPLETE=Operation Complete"
set "CONTINUE_PROMPT=Run another operation? (Y/N): "
set "DONE=Operation finished."
set "CLOSE_PROMPT=Press any key to close this window..."
set "GENERATED_FILES=Check the generated files:"
set "PROJECT_ROOT_LABEL=Project root:"
set "EXTRACT_MISSING=[ERROR] Extracted image folder was not found:"
set "EXTRACT_HINT=Extract images first or check that the extracted folder exists."
set "REPACK_TARGET=Repack target:"

if /I "%TOOL_VENDOR%"=="ASUS" (
    set "TITLE=ASUS BIOS Image Analysis/Repack Tool"
    set "BANNER_TITLE=ASUS BIOS Image Analysis/Repack Tool v3.0"
    set "TIP_DRAG=  - Drag an ASUS BIOS file onto this batch file"
    set "MENU1=1. [Analyze] Analyze ASUS BIOS file"
    set "MENU1D1=   - Analyze file structure and magic bytes"
    set "MENU1D2=   - Detect ASUS Packer format"
    set "MENU1D3=   - Generate analysis reports TXT/MD"
    set "MENU2=2. [Repack] Repack ASUS images"
    set "MENU2D1=   - Repackage modified images"
    set "MENU2D2=   - Preserve original structure as much as possible"
    set "MENU2D3=   - Handle size changes automatically"
    set "ANALYZE_HEADER=[ANALYZE] ASUS BIOS File Analysis"
    set "REPACK_HEADER=[REPACK] ASUS Image Repack"
) else (
    set "TITLE=MSI BIOS Analysis/Repack Tool"
    set "BANNER_TITLE=MSI BIOS Section Binary Analysis/Repack Tool v1.0"
    set "TIP_DRAG=  - Drag an MSI BIOS file onto this batch file"
    set "MENU1=1. [Analyze] Analyze MSI BIOS file"
    set "MENU1D1=   - Analyze MSI Packer structure"
    set "MENU1D2=   - Check image types and magic bytes"
    set "MENU1D3=   - Generate analysis report"
    set "MENU2=2. [Repack] Repack MSI images"
    set "MENU2D1=   - Repackage extracted images"
    set "MENU2D2=   - Preserve original structure"
    set "MENU2D3=   - Requires msi_extracted folder"
    set "ANALYZE_HEADER=[ANALYZE] MSI BIOS File Analysis"
    set "REPACK_HEADER=[REPACK] MSI Image Repack"
)
goto :eof
